name: Downgrade azure-cli on GitHub hosted runner

on:
  workflow_dispatch:

jobs:
  # linux-regression:
  #   runs-on: ubuntu-latest
  #   steps:
  #      - name: uninstall azure-cli 
  #        run: |
  #           sudo apt-get remove -y azure-cli
  #      - name: install azure-cli 2.58.0
  #        run: |
  #           sudo apt-get update
  #           sudo apt-get install apt-transport-https ca-certificates curl gnupg lsb-release
  #           sudo mkdir -p /etc/apt/keyrings
  #           curl -sLS https://packages.microsoft.com/keys/microsoft.asc |
  #               sudo gpg --dearmor -o /etc/apt/keyrings/microsoft.gpg
  #           sudo chmod go+r /etc/apt/keyrings/microsoft.gpg
  #           AZ_DIST=$(lsb_release -cs)
  #           echo "Types: deb
  #           URIs: https://packages.microsoft.com/repos/azure-cli/
  #           Suites: ${AZ_DIST}
  #           Components: main
  #           Architectures: $(dpkg --print-architecture)
  #           Signed-by: /etc/apt/keyrings/microsoft.gpg" | sudo tee /etc/apt/sources.list.d/azure-cli.sources
  #           AZ_VER=2.58.0
  #           sudo apt-get update && sudo apt-get install azure-cli=${AZ_VER}-1~${AZ_DIST}
  #      - name: check azure-cli version
  #        run: |
  #           az --version
            
  windows-regression:
    runs-on: windows-latest
    steps:
       - name: uninstall azure-cli 
         run: |
            az --version
            $ProgressPreference = 'SilentlyContinue'; 
            Invoke-WebRequest -Uri
            https://azcliprod.blob.core.windows.net/msi/azure-cli-2.59.0.msi
            -OutFile .\azure-cli-2.59.0.msi; 
            Start-Process msiexec.exe -Wait -ArgumentList ' /X azure-cli-2.59.0.msi /quiet'; 
            az --version
            Remove-Item .\azure-cli-2.59.0.msi
            Invoke-WebRequest -Uri
            https://azcliprod.blob.core.windows.net/msi/azure-cli-2.58.0.msi
            -OutFile .\azure-cli-2.58.0.msi; 
            Start-Process msiexec.exe -Wait -ArgumentList ' /I azure-cli-2.58.0.msi /quiet'; 
            az --version
            Remove-Item .\azure-cli-2.58.0.msi


