name: Run GitHub issue copilot
on:
  issues:
    types: [opened, edited, closed]

jobs:
  Issue:
     permissions:
        issues: write
     runs-on: ubuntu-latest
     steps:
     - name: Run GitHub issue copilot
       uses: MoChilia/IssueCopilot@dev
       with:
         password: ${{secrets.COPILOT_PASSWORD}}
