name: Run issue sentinel
on:
  issues:
      types: [opened, edited, closed]

jobs:
  Issue:
      permissions:
          issues: write
      runs-on: ubuntu-latest
      steps:
      - name: Run Issue Sentinel
        uses: azure/issue-sentinel@dependabot/npm_and_yarn/form-data-4.0.4
        with:
          password: ${{secrets.COPILOT_PASSWORD}}
          enable-similar-issues-scanning: true # Scan similar issues in your repo, default: true
          enable-security-issues-scanning: true # Scan security issues in your repo, default: false
