name: Test AZURE_CORE_OUTPUT at job level

on:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      AZURE_CORE_OUTPUT: None
      
    steps:
      - name: Azure CLI script
        uses: azure/cli@v1
        with:
          inlineScript: |
            az version
          
      - name: run az cli in shell
        run: |
          az version
          
      - name: Test failed Azure CLI script
        continue-on-error: true
        uses: azure/cli@v1
        with:
          inlineScript: |
            az account show
