name: Test AZURE_CORE_OUTPUT at workflow level

on:
  workflow_dispatch:

env:
  AZURE_CORE_OUTPUT: None
  
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: Azure CLI script
        uses: azure/cli@v1
        with:
          inlineScript: |
            az version
          
      - name: run az cli in shell
        run: |
          az version

  test2:
    runs-on: windows-latest
    steps:
      - name: Azure CLI script
        uses: azure/cli@v1
        with:
          inlineScript: |
            az version
          
      - name: run az cli in shell
        run: |
          az version
